# Generated by Django 5.2.7 on 2025-10-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verification_token_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
