# Generated by Django 4.2.16 on 2025-12-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_userprofile_verification_token_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("admin", "Admin")],
                default="user",
                max_length=10,
                verbose_name="Rol",
            ),
        ),
    ]
