# Generated by Django 4.2.16 on 2025-12-06 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tasks_api.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=tasks_api.models.attachment_upload_path,
                        validators=[
                            tasks_api.models.validate_file_size,
                            tasks_api.models.validate_file_type,
                        ],
                        verbose_name="Dosya",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="Orijinal Dosya Adı"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(verbose_name="Dosya Boyutu (bytes)"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yüklenme Tarihi"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="tasks_api.task",
                        verbose_name="Görev",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yükleyen Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Görev Eklentisi",
                "verbose_name_plural": "Görev Eklentileri",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
